### ISSUE TITLE
Apps install

### ISSUE THREAD

**Issue by Silence714** [dat-linux/community#42]
I've installed DAT Linux on Vm, network is fine and I can open WEB on my Browser . But It doesn't install the Apps .. I attach the screenshot. 
![Screenshot (2)](https://github.com/dat-linux/community/assets/152275289/016f9e01-ac2f-4af1-9d52-1c369181f663)

**Comment by dat-linux** [comment]
Hi, please post to the discussion area.

There may have been a problem connecting to the github backend, please try again.
