### ISSUE TITLE
Reset default display settings

### ISSUE THREAD

**Issue by quadeqx** [dat-linux/community#47]
I was familiarizing myself with this wonderful Linux distro and some display settings changed as shown in the attached image. This has caused title bars to be bigger than normal, the system info and also the data science control panel. Is there a way to default this. I've tried to run <dconf reset -f /> but nothing changed

![control_panel](https://github.com/dat-linux/community/assets/154374993/62526b75-5081-4572-88ce-261198294f61)

**Comment by dat-linux** [comment]
This is not what this area is for, please post on the community discussions.
